[package]
name = "client"
version = "0.0.1"
edition = "2021"

[dependencies]
lib_common = {path ="../lib_common"}
serde = { version= "1", features=["derive"] }
serde_json = "1"
rand = "0.8.5"
md5 = "0.7.0"
byteorder = "1"
